config/routes.rb
Lodgistics::Application.routes.draw do
  require 'sidekiq/web'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    # registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }, skip: [:registrations]

  %w( 403 404 500 ).each do |code|
    get code, to: "errors#show", code: code
  end

  namespace :corporate do
    root to: 'pages#dashboard'
    resources :settings, only: [:index]
    resources :property_connections, only: [:show, :update]
    resources :purchase_requests, only: [:edit, :update], path: 'requests'
    get '/spend_budget_by_hotel_data' => 'pages#spend_budget_by_hotel', as: 'spend_budget_by_hotel_data'
    get '/work_order_clouds' => 'pages#work_order_clouds', as: 'work_order_clouds'
    get '/open_work_order_by_hotel' => 'pages#open_work_orders_by_hotel', as: 'open_work_orders_by_hotel'
  end
  
  namespace :maintenance do
    root to: 'pages#dashboard' # probably need to move it under /dashboard, @HUGO
    get :setup, to: 'setup#index', as: :setup
    get '/setup/rooms', to: 'setup#rooms', as: :setup_rooms
    get '/setup/public_areas', to: 'setup#public_areas', as: :setup_public_areas
    get '/setup/equipment', to: 'setup#equipment', as: :setup_equipment
    resources :rooms, only: [:show, :index, :create, :update] do
      get :inspection, on: :collection
      get :inspect, on: :member
    end
    resources :checklist_items, only: [:index, :create, :update,:destroy]
    resources :cycles, only: [:create] do
      post :create_next, on: :collection
    end
    resources :checklist_item_maintenances, only: [:index, :create, :destroy] do
      member do
        post :inspect
        delete :cancel_inspect
      end

      collection do
        get :equipment
      end
    end
    resources :public_areas, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :checklist_items
        get :inspection
      end
      get :inspect, on: :member
    end
    resources :records, only: [:index, :update, :destroy] do
      member do
        post :complete_inspection
        post :cancel_inspection
      end
    end
    resources :work_orders
    resources :materials, only: [:index, :create, :update, :destroy]
    resources :equipment_types, only: [:index, :create, :update, :destroy] do
      resources :equipment_checklist_items, only: [:index, :create, :show, :update, :destroy]
    end
    resources :equipments, only: [:index, :show, :create, :update, :destroy]

    get '/week_vs_completed_rooms_data' => 'pages#week_vs_completed_rooms_data', as: 'week_vs_completed_rooms_data'
    get '/pm_room_progress_data' => 'pages#pm_room_progress_data', as: 'pm_room_progress_data'
  end

  namespace :admin do
    root to: 'pages#dashboard'
    resources :users, only: [:edit, :update]
    resources :customers, only: [:new, :create, :show]
  end

  devise_for :admins, path: 'admin', controllers: {
                        sessions: 'admin/sessions',
                        passwords: 'admin/passwords'
                      }

  resource :corporate_connections

  get :spend_vs_budgets_data, to: 'pages#spend_vs_budgets_data'

  authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  authenticated :admin do
    root 'pages#dashboard', as: :admin_authenticated_root
  end

  devise_scope :user do
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
    namespace :users, as: :user do
      put "/confirm" => "confirmations#confirm", as: :confirm
      put '/switch_current_property', to: 'sessions#switch_current_property', as: :switch_current_property
      resource :registration, only: [:edit, :update]
    end
  end
  resources :property_settings, path: 'settings', only: [:index]
  resources :categories, :locations, :lists do
    get 'rearrange', on: :member
    get 'destroy', on: :collection, path: 'destroy', as: 'destroy'
  end  
  resources :items do
    collection do
      get 'start_order'
      get 'edit_multiple_tags'
      put 'update_multiple_tags'
      get :new_import
      post :import
      get 'destroy', path: 'destroy', as: 'destroy'
    end
  end
  resources :permissions, only: [:index] do
    collection do
      post 'update_all'
    end
  end
  resources :properties, only: [:show, :index, :update]
  resources :tags do
    get 'rearrange', on: :member
  end
  resources :purchase_orders, except: [:edit, :new, :create], path: 'orders' do
    member do
      post :send_fax, to: 'fax#create'
      get :fax_status, to: 'fax#show'
      post :update_fax, to: 'fax#update'
      post :send_email, to: 'email#create'
      post :send_vpt, to: 'vpt#create'
      get :print
    end
  end
  resources :purchase_receipts, only: [:new, :create], path: 'receipts'
  resources :purchase_requests, path: 'requests' do
    member do
      get :inventory_print
    end
  end
  resources :users do
    member do
      get :change_password
    end
  end
  resources :messages
  resources :budgets

  resources :reports do
    member do
      put :favorite
    end
    collection do
      get :favorites
      #get *Report.pluck(:permalink).map{|p| p + '_data'} if Report.any?
      get :trending_cloud
      scope :render do
        get :vendor_spend
        get :category_spend
        get :items_consumption
        get :item_orders_chart_data
        get :items_spend
        get :item_price_variance
        get :inventory_vs_ordering
        get :maintenance_work_orders
        get :pm_productivity_report
        get :maintenance_pm_productivity_data
        get :room_pm_progress_data
        get :work_order_productivity_data
        get :guest_room_pm_analysis
        get :public_area_pm_analysis
        get :equipment_pm_analysis
        get :work_order_trendings
      end
    end
  end


  resources :vendors
  resources :room_types
  resources :departments
  resources :notifications
  resources :activities, only: [:index]
  resources :join_invitations do
    get 'accept', on: :member
  end
  resources :guest_logs do
    get 'like', on: :member
    post 'set_alarm', on: :collection
    get 'check_alarm', on: :member
    delete 'remove_alarm', on: :member
  end

  post 'punchout/:property_id/:vendor_id/shopping_cart', to: "punchout#shopping_cart", as: 'punchout_shopping_cart'
  get 'punchout/:property_id/:vendor_id', to: "punchout#create", as: 'start_punchout'

  get 'analytics', to: "analytics#index"
  get 'forecasts/(week/:year/:month/:day)', to: "forecasts#index", as: "forecasts"
  put 'forecast', to: "forecasts#update", as: "update_forecast"

  get '/fax', to: 'fax#show'
  post '/fax', to: 'fax#create'
  post '/phaxio', to: 'fax#update'
  get 'dashboard', to: 'pages#dashboard', :as => :dashboard
  get 'pages/home'
  # authenticated :user do
  #   root to: 'pages#dashboard'
  # end

  #root to: 'users/sessions#new'  
  if Rails.env.development? or Rails.env.qa?
    mount MailerPreview => 'mailer_view'
    mount Sidekiq::Web, at: '/sidekiq'
  end

end

app/models/maintenance.rb
module Maintenance
  def self.table_name_prefix
    'maintenance_'
  end
end

app/models/maintenance/attachment.rb
class Maintenance::Attachment < ActiveRecord::Base

  belongs_to :equipmentable, polymorphic: true
  mount_uploader :file, EquipmentAttachmentUploader

end

app/models/maintenance/inspection_detail.rb
class Maintenance::InspectionDetail < ActiveRecord::Base

  belongs_to :work_order, class_name: 'Maintenance::WorkOrder', foreign_key: :work_order_id
  belongs_to :checklist_item_maintenance, class_name: 'Maintenance::ChecklistItemMaintenance', foreign_key: :checklist_item_maintenance_id

end

app/controllers/maintenance/base_controller.rb
class Maintenance::BaseController < ApplicationController
  before_filter :authenticate_user!
  before_action :check_permissions
  before_action :check_current_cycles_are_finished

  add_breadcrumb I18n.t("controllers.maintenance.root"), :maintenance_root_path

  private

  def check_permissions
    authorize :access, :maintenance?
  end

  # returns an array of cycles that are finished by the moment of checking
  # example: [:room]
  def check_current_cycles_are_finished
    finished_cycles = Maintenance::Cycle::CYCLE_TYPES
    .map{ |c_type| current_cycle(c_type) }.compact
    .select{ |cycle| cycle.is_over? }
    # to test messages uncomment next line:
    # finished_cycles = [current_cycle(:room), current_cycle(:public_area)]
    messages = render_to_string(partial: 'maintenance/shared/cycle_expired_alert', locals: {finished_cycles: finished_cycles})
    flash[:sticky_messages] = [[:alert, messages]] if finished_cycles.any?
  end

  def send_notification_and_mail_to_assignee(work_order)
    if @work_order.assigned_to
      MaintenanceWorkOrderMailer.work_order_notification_to_assignee(work_order).deliver!
      Notification.assigned_work_order(work_order)
      WorkOrderWorker.perform_async(work_order.id)
    end
  end

  def authorize_maintenance
    authorize :access, :pm?
  end

  def authorize_inspection
    authorize :access, :inspection?
  end

  def authorize_work_order
    authorize :access, :work_order?
  end

  def authorize_pm_setup
    authorize :access, :pm_setup?
  end

end

app/controllers/maintenance/checklist_item_maintenances_controller.rb
class Maintenance::ChecklistItemMaintenancesController < Maintenance::BaseController

  before_filter :get_maintainable, only: [:index, :create, :inspect, :equipment]

  def index
    render json: @maintainable.maintenance_records.find(params[:record_id]).to_json(
         include: { checklist_item_maintenances: { include: [:work_order, :inspection_work_order] } }
      ), status: 200
  end

  def equipment
    render json: @maintainable.maintenance_records.where(id: params[:record_id]).first.to_json(
               include: { checklist_item_maintenances: { include: [:work_order, :inspection_work_order] } }
           ), status: 200
  end

  def create
    if !policy(Maintenance::ChecklistItemMaintenance).single_click_pm? && params[:checklist_item_ids] && params[:checklist_item_ids].count > 1
      render json: {message: 'You are not authroized to do single click PM'}, status: 401 and return
    end
    if params[:record_id]
      @record = @maintainable.maintenance_records.find params[:record_id]
    else
      @record = @maintainable.maintenance_records.for_cycle(params[:cycle_id])
    end
    checklist_item_ids = (params[:checklist_item_ids] || []).map(&:to_i) - @record.checklist_item_maintenances.pluck(:maintenance_checklist_item_id)
    item_maintenance_ids = []
    checklist_item_ids.each do |item_id|
      checklist_item_maintenance = @record.checklist_item_maintenances.find_or_initialize_by(maintenance_checklist_item_id: item_id)

      if params[:status] == Maintenance::ChecklistItemMaintenance::STATUS_ISSUES.to_s
        checklist_item_maintenance.update_attributes status: params[:status]

        work_order = Maintenance::WorkOrder.new(work_order_params)
        work_order.checklist_item_maintenance = checklist_item_maintenance
        work_order.opened_by = current_user
        work_order.maintainable = @maintainable
        work_order.opened_at = Time.current
        work_order.status = Maintenance::WorkOrder::STATUS_OPEN
        work_order.assigned_to_id = current_user.wo_assignable_id
        work_order.priority = 'l'
        work_order.save
      else
        checklist_item_maintenance.update_attributes(status: params[:status], comment: params[:comment])
      end
      item_maintenance_ids << checklist_item_maintenance.id
    end

    @checklist_item_maintenances = @record.checklist_item_maintenances.where(id: item_maintenance_ids)
    render json: @checklist_item_maintenances.to_json(include: :work_order), status: 200
  end

  def inspect
    @checklist_item_maintenance = Maintenance::ChecklistItemMaintenance.find params[:id]
    @inspection_detail = @checklist_item_maintenance.build_inspection_detail
    @work_order = @inspection_detail.build_work_order
    @work_order.maintainable = @maintainable
    @work_order.description = params[:comment]
    @work_order.opened_by = current_user
    @work_order.opened_at = Time.current
    @work_order.status = Maintenance::WorkOrder::STATUS_OPEN
    @work_order.priority = 'l'
    @work_order.checklist_item_maintenance = @checklist_item_maintenance
    completed_by = @checklist_item_maintenance.maintenance_record.completed_by
    @work_order.assigned_to_id = (completed_by && completed_by.wo_assignable_id) || Maintenance::WorkOrder::UNASSIGNED

    @inspection_detail.save

    render json: @inspection_detail.to_json(include: :work_order), status: 200
  end

  def cancel_inspect
    @checklist_item_maintenance = Maintenance::ChecklistItemMaintenance.find params[:id]
    @inspection_work_order = @checklist_item_maintenance.inspection_work_order
    @inspection_work_order.destroy

    render json: @checklist_item_maintenance.id, status: 200
  end

  def destroy
    @checklist_item_maintenance = Maintenance::ChecklistItemMaintenance.find params[:id]
    @checklist_item_maintenance.destroy
    render json: params[:id], status: 200
  end

  private

  def get_maintainable
    @maintainable = params[:maintainable_type].classify.constantize.find(params[:maintainable_id])
  end

  def work_order_params
    params.require(:maintenance_work_order).permit(
      :status, :description, :priority, :assigned_to_id, :maintainable_id, :maintainable_type, :other_maintainable_location, :due_to_date,
      attachments_attributes: [:id, :file, :_destroy ]
    )
  end

end

app/controllers/maintenance/checklist_items_controller.rb
class Maintenance::ChecklistItemsController < Maintenance::BaseController
  before_action :set_maintenance_checklist_item,only: [:update,:destroy]
  skip_before_action :check_current_cycles_are_finished

  def index
    @checklist_items = Maintenance::ChecklistItem.areas_with_subcategories
    render json: @checklist_items.to_json
  end

  def create
    @checklist_item = Maintenance::ChecklistItem.new checklist_item_params
    @checklist_item.user_id = current_user.id
    @checklist_item.save
    render json: @checklist_item.to_json(only: [:id, :name, checklist_items: []]), status: 200
  end

  def update
    @checklist_item.update checklist_item_params
    render nothing: true, status: 200
  end
  
  def destroy
    @checklist_item.update_attribute(:is_deleted, true)
    render nothing: true, status: 200
  end

  private
  
  def set_maintenance_checklist_item
    @checklist_item = Maintenance::ChecklistItem.find params[:id]
  end

  def checklist_item_params
    params.require(:checklist_item).permit(
        :name,
        :area_id,
        :maintenance_type,
        :public_area_id,
        :area_row_order_position,
        :item_row_order_position,
        :public_area_row_order_position
    )
  end
end

app/controllers/maintenance/cycles_controller.rb
class Maintenance::CyclesController < Maintenance::BaseController

  def create
    @cycle = current_cycle params[:cycle_type]
    params[:user_id] = current_user.id
    if @cycle.blank?
      @cycle = Maintenance::Cycle.generate_first_cycle params if @cycle.nil?
      if @cycle.valid?
        render json: { cycle: @cycle, message: 'Cycle Frequency updated.' }, status: 200
      else
        render json: { error: @cycle.errors.full_messages.to_sentence }, status: 400
      end
    else
      render json: { error: 'You already setup cycle.' }, status: 409
    end
  end

  # post /maintenance/cycles/create_next
  # creates a next cycle record
  def create_next
    old_cycles = Maintenance::Cycle::CYCLE_TYPES.map { |type| Maintenance::Cycle.current(type) }.select{ |cycle| cycle && cycle.is_over? }
    cycles = []
    for old_cycle in old_cycles
      cycles << Maintenance::Cycle.generate_next_cycle( old_cycle.cycle_type )
    end
    render json: cycles.map{|cycle| {cycle_number: cycle.ordinality_number, cycle_type: cycle.cycle_type_desc, year: cycle.year } }.to_json
  end

end

app/controllers/maintenance/equipment_checklist_items_controller.rb
class Maintenance::EquipmentChecklistItemsController < Maintenance::BaseController
  before_filter :get_equipment_type

  def create
    @checklist_item = @equipment_type.checklist_items.build checklist_item_params
    if @checklist_item.save
      render json: @checklist_item.to_json(include: :checklist_items), status: 200
    else
      render json: @checklist_item.errors.full_messages.to_sentence, status: 422
    end
  end

  def show
    @checklist_item = @equipment_type.checklist_items.find params[:id]
    render json: @checklist_item.to_json(include: :checklist_items), status: 200
  end

  def update
    @checklist_item = @equipment_type.checklist_items.find params[:id]
    if @checklist_item.update_attributes checklist_item_params
      render json: @checklist_item.to_json(include: :checklist_items), status: 200
    else
      render json: @checklist_item.errors.full_messages.to_sentence, status: 422
    end
  end

  def destroy
    @checklist_item = @equipment_type.checklist_items.find params[:id]
    if @checklist_item.destroy
      render json: @checklist_item.id
    else
      render json: {error: 'Failed to delete Equipment Type'}, status: 422
    end
  end

  private

  def get_equipment_type
    @equipment_type = Maintenance::EquipmentType.find params[:equipment_type_id]
  end

  def checklist_item_params
    params.require(:checklist_item).permit(:name, :frequency, :tools_required, :group_id, :row_order_position)
  end
end

app/views/maintenance/setup/equipment.html.slim
- body_class 'equipment-setup-page'
.page-header.page-header-block.pb0
  .pb15.clearfix
    .pull-left
      h4.title.semibold Setup Types of Equipment
    .pull-right
      a.btn.btn-primary.add-equipment-type
        span.ico-plus-sign
        '
        | Add Equipment Type

.row
  .col-md-12
    #equipment-types
      .panel-group.items-listing

script#equipment-type-template type="x-tmpl-mustache"
  div class="panel equipment-type-item {{panel_class}}" data-id="{{id}}"
    .panel-heading.btn-default
      h4.panel-title
        i.area-sort-handle.ico-sort.mr10
        a.collapsed.equipment-type-toggler data-toggle="collapse" href="#collapse-{{id}}"
          span.plus.mr10
        a.equipment-type-name href="#"
          | {{name}}
          span.equipment-type-info
        = link_to 'javascript:void(0)', class: 'pull-right equipment-type-delete', data: {confirm: 'Do you want to delete equipment type?'} do
          i.ico-trash
    div.panel-collapse.collapse id="collapse-{{id}}"
      .panel-body
        .row
          .col-md-6
            .panel.panel-default.panel-checklist-groups
              .panel-heading
                h4.panel-title Checklists
                .panel-toolbar.text-right.hidden
                  a.btn.btn-primary.btn-outline.add-group
                    span.ico-plus-sign
                    '
                    | New Checklist
              .panel-body
                .panel-group.items-listing
                  | {{#checklist_groups}}
                  | {{>checklist_group}}
                  | {{/checklist_groups}}
                  .no-checklist-groups.text-center.hidden
                    p You do not have any groups created.
                    a.btn.btn-primary.btn-outline.add-group
                      span.ico-plus-sign
                      '
                      | Create first Checklist
          .col-md-6
            .panel.panel-default.panel-equipments
              .panel-heading
                h4.panel-title Equipment
                .panel-toolbar.text-right.hidden
                  a.btn.btn-primary.btn-outline.add-equipment
                    span.ico-plus-sign
                    '
                    | New Equipment
              .panel-body
                .panel-group.equipments-listing
                  | {{#active_equipments}}
                  | {{>active_equipment}}
                  | {{/active_equipments}}
                  .no-equipments.text-center.hidden
                    p You do not have any equipments created.
                    a.btn.btn-primary.btn-outline.add-equipment
                      span.ico-plus-sign
                      '
                      | Create first Equipment

script#checklist-group-template type="x-tmpl-mustache"
  .panel.checklist-group data-id="{{id}}"
    .panel-heading
      h5
        i.checklist-sort-handle.ico-sort.mr10
        a.checklist-group-name href="#"
          | {{name}} (<span class="item-count">{{item_count}}</span> items)
        = link_to 'javascript:void(0)', class: 'pull-right checklist-group-delete', data: {confirm: 'Do you want to delete checklist?'} do
          i.ico-trash.text-danger

script#equipment-template type="x-tmpl-mustache"
  .panel.equipment-item data-id="{{id}}"
    .panel-heading
      h5
        i.equipment-sort-handle.ico-sort.mr10
        a.equipment-name href="#"
          | {{name}} ({{location}})
        = link_to 'javascript:void(0)', class: 'pull-right equipment-delete', data: {confirm: 'Do you want to delete equipment?'} do
          i.ico-trash.text-danger

script#checklist-item-template type="x-tmpl-mustache"
  .panel.checklist-item data-id="{{id}}"
    .panel-heading
      h5
        i.item-sort-handle.ico-sort.mr10
        a
          span.count
          | )&nbsp;
        a.checklist-item-name.x-editable href="#" data-title="Edit Checklist Item" data-type="text" data-url="{{update_url}}" data-send="always"
          | {{name}}
        = link_to 'javascript:void(0)', class: 'pull-right checklist-item-delete', data: {confirm: 'Do you want to delete checklist item?'} do
          i.ico-trash.text-danger

#equipment-type-modal.modal.fade
  .modal-dialog

script#equipment-type-form-template type="x-tmpl-mustache"
  form.modal-content id="equipment-type-form" data-parsley-validate=true
    .modal-header
      .cell.text-center
        button.close data-dismiss="modal" type="button" ×
        h4.semibold.text-primary.modal-title Enter Equipment Type
    .modal-body
      .form-group
        label.control-label for="equipment-type-name" Name
        span.text-danger *
        input type="text" class="form-control" placeholder="Enter name" id="equipment-type-name" value="{{name}}" required=true
      .form-group
        label.control-label for="instruction-description" Instruction description
        textarea class="form-control" rows=3 placeholder="Enter instruction description" id="instruction-description" {{instruction}}
      .form-group
        .attachment
          label.control-label for="attachment" Attachment file
          | {{#attachment.file.url}}
          .attachment-info.pull-right data-id="{{attachment.id}}"
            a.inline-block.mr10 href="{{attachment.file.url}}" target="_blank" {{attachment.file.name}}
            a.inline-block.text-danger.delete-attachment href="#" data-type="equipment_type" data-id="{{id}}" data-confirm="Do you want to delete attachment?"
              span.ico-remove
              '
              | Delete Attachment
          | {{/attachment.file.url}}
          .input-group
            input type="text" class="form-control" readonly="" id="attachment-name" placeholder="{{#attachment.file.url}}Replace current attachment{{/attachment.file.url}}"
            span.input-group-btn
              .btn.btn-primary.btn-file
                span.icon.iconmoon-file-3
                  | Browse
                  input type="file" id="attachment"
    .modal-footer
      button.btn.btn-default.btn-expanded data-dismiss="modal" type="button" Cancel
      input.btn.btn-primary.btn-expanded type="submit" id="equipment-type-form-submit" value="Save"

#equipment-checklist-item-modal.modal.fade
  .modal-dialog

script#equipment-checklist-item-form-template type="x-tmpl-mustache"
  form.modal-content id="equipment-checklist-item-form" data-parsley-validate=true data-group-id="{{id}}" data-type-id="{{type_id}}"
    .modal-header
      .cell.text-center
        button.close data-dismiss="modal" type="button" ×
        h4.semibold.text-primary.modal-title
          | {{^id}}
          | New Checklist for '{{type_name}}'
          | {{/id}}
          | {{#id}}
          | Edit Checklist '{{name}}'
          | {{/id}}
    .modal-body
      .form-group.text-right
        button.btn.btn-default.btn-expanded data-dismiss="modal" type="button" Cancel
        input.btn.btn-success.ml5.btn-expanded#checklist-group-form-submit type="submit" disabled="disabled" value="Save"
      .form-group
        .row
          .col-sm-6
            label.control-label for="checklist-item-name" Name
            span.text-danger *
            input type="text" class="form-control" placeholder="Enter name" id="checklist-group-name" value="{{name}}" required=true
          .col-sm-6
            label.control-label for="frequency" Maintain Equipment every
            span.text-danger *
            = select_tag :frequency,
                         options_for_select(Maintenance::EquipmentChecklistItem::FREQUENCIES, selected='1'),
                         class: 'form-control', required: true
      .form-group
        label.control-label for="tools-required" Tools Required
        textarea class="form-control" rows=5 placeholder="Enter required tools" id="tools-required" {{tools_required}}
      #checklist-items-panel class="{{^id}}hidden{{/id}}"
        hr
        .form-group
          .input-group
            input.form-control type="text" id="checklist-item-name" placeholder="Enter Item name here"
            span.input-group-btn
              a.btn.btn-default.add-item
                span.ico-plus-sign
                '
                | Save Checklist Item
        .form-group
          .panel-group.items-listing
            | {{#checklist_items}}
            | {{>checklist_item}}
            | {{/checklist_items}}
    .modal-footer

#equipment-modal.modal.fade
  .modal-dialog

script#equipment-form-template type="x-tmpl-mustache"
  form.modal-content id="equipment-form" data-parsley-validate=true
    .modal-header
      .cell.text-center
        button.close data-dismiss="modal" type="button" ×
        h4.semibold.text-primary.modal-title
          | {{^id}}
          | New Equipment for '{{type_name}}'
          | {{/id}}
          | {{#id}}
          | {{name}} ({{location}})
          | {{/id}}
    .modal-body
      .form-group
        .row
          .col-sm-6
            label.control-label for="equipment-name" Name
            span.text-danger *
            input type="text" class="form-control" placeholder="Enter name" id="equipment-name" value="{{name}}" required=true
          .col-sm-6
            label.control-label for="equipment-location" Location
            span.text-danger *
            input type="text" class="form-control" placeholder="Enter location" id="equipment-location" value="{{location}}" required=true
      .form-group
        .row
          .col-sm-6
            label.control-label for="equipment-buy-date" Buy Date
            input type="text" class="form-control datepicker" placeholder="Enter buy date" id="equipment-buy-date" value="{{buy_date}}"
          .col-sm-6
            label.control-label for="equipment-replacement-date" Replacement Date
            input type="text" class="form-control datepicker" placeholder="Enter replacement date" id="equipment-replacement-date" value="{{replacement_date}}"
      .form-group
        .row
          .col-sm-6
            label.control-label for="equipment-warranty" Warranty Period
            input type="text" class="form-control numeric-input" placeholder="Enter warranty period" id="equipment-warranty" value="{{warranty}}"
          .col-sm-6
            label.control-label for="equipment-lifespan" Expected Lifespan
            input type="text" class="form-control numeric-input" placeholder="Enter expected lifespan" id="equipment-lifespan" value="{{lifespan}}"
      .form-group
        .row
          .col-sm-12
            label.control-label for="equipment-make" Make
            input type="text" class="form-control" placeholder="Enter make" id="equipment-make" value="{{make}}"
      .form-group
        .row
          .col-sm-12
            label.control-label for="equipment-instruction-description" Instruction description
            textarea class="form-control" rows=3 placeholder="Enter instruction description" id="equipment-instruction-description" {{instruction}}
      .form-group
        .attachment
          label.control-label for="attachment" Attachment file
          | {{#attachment.file.url}}
          .attachment-info.pull-right data-id="{{attachment.id}}"
            a.inline-block.mr10 href="{{attachment.file.url}}" target="_blank" {{attachment.file.name}}
            a.inline-block.text-danger.delete-attachment href="#" data-type="equipment" data-id="{{id}}" data-type-id="{{equipment_type_id}}" data-confirm="Do you want to delete attachment?"
              span.ico-remove
              '
              | Delete Attachment
          | {{/attachment.file.url}}
          .input-group
            input type="text" class="form-control" readonly="" id="attachment-name" placeholder="{{#attachment.file.url}}Replace current attachment{{/attachment.file.url}}"
            span.input-group-btn
              .btn.btn-primary.btn-file
                span.icon.iconmoon-file-3
                  | Browse
                  input type="file" id="equipment-attachment"
    .modal-footer
      | {{#id}}
      - if current_user.current_property_role.gm?
        = link_to 'Remove from use', '#', class: 'btn btn-danger', id: 'remove-equipment', data: {id: '{{id}}', 'type-id' => '{{equipment_type_id}}', confirm: 'Do you want to remove the equipment \'{{name}}\'?'}
      | {{/id}}
      button.btn.btn-default.btn-expanded data-dismiss="modal" type="button" Cancel
      input.btn.btn-primary.btn-expanded#equipment-form-submit type="submit" value="Save"

app/views/maintenance/setup/index.html.slim
.row
  .col-md-6
    .panel.panel-default
      .panel-body
        h3= link_to 'Guest Rooms', maintenance_setup_rooms_path
  .col-md-6
    .panel.panel-default
      .panel-body
        h3= link_to 'Public Areas',maintenance_setup_public_areas_path
.row
  .col-md-6
    .panel.panel-default
      .panel-body
        h3= link_to 'Equipment', maintenance_setup_equipment_path