config/routes.rb
Lodgistics::Application.routes.draw do
  require 'sidekiq/web'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    # registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }, skip: [:registrations]

  %w( 403 404 500 ).each do |code|
    get code, to: "errors#show", code: code
  end

  namespace :corporate do
    root to: 'pages#dashboard'
    resources :settings, only: [:index]
    resources :property_connections, only: [:show, :update]
    resources :purchase_requests, only: [:edit, :update], path: 'requests'
    get '/spend_budget_by_hotel_data' => 'pages#spend_budget_by_hotel', as: 'spend_budget_by_hotel_data'
    get '/work_order_clouds' => 'pages#work_order_clouds', as: 'work_order_clouds'
    get '/open_work_order_by_hotel' => 'pages#open_work_orders_by_hotel', as: 'open_work_orders_by_hotel'
  end
  
  namespace :maintenance do
    root to: 'pages#dashboard' # probably need to move it under /dashboard, @HUGO
    get :setup, to: 'setup#index', as: :setup
    get '/setup/rooms', to: 'setup#rooms', as: :setup_rooms
    get '/setup/public_areas', to: 'setup#public_areas', as: :setup_public_areas
    get '/setup/equipment', to: 'setup#equipment', as: :setup_equipment
    resources :rooms, only: [:show, :index, :create, :update] do
      get :inspection, on: :collection
      get :inspect, on: :member
    end
    resources :checklist_items, only: [:index, :create, :update,:destroy]
    resources :cycles, only: [:create] do
      post :create_next, on: :collection
    end
    resources :checklist_item_maintenances, only: [:index, :create, :destroy] do
      member do
        post :inspect
        delete :cancel_inspect
      end

      collection do
        get :equipment
      end
    end
    resources :public_areas, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :checklist_items
        get :inspection
      end
      get :inspect, on: :member
    end
    resources :records, only: [:index, :update, :destroy] do
      member do
        post :complete_inspection
        post :cancel_inspection
      end
    end
    resources :work_orders
    resources :materials, only: [:index, :create, :update, :destroy]
    resources :equipment_types, only: [:index, :create, :update, :destroy] do
      resources :equipment_checklist_items, only: [:index, :create, :show, :update, :destroy]
    end
    resources :equipments, only: [:index, :show, :create, :update, :destroy]

    get '/week_vs_completed_rooms_data' => 'pages#week_vs_completed_rooms_data', as: 'week_vs_completed_rooms_data'
    get '/pm_room_progress_data' => 'pages#pm_room_progress_data', as: 'pm_room_progress_data'
  end

  namespace :admin do
    root to: 'pages#dashboard'
    resources :users, only: [:edit, :update]
    resources :customers, only: [:new, :create, :show]
  end

  devise_for :admins, path: 'admin', controllers: {
                        sessions: 'admin/sessions',
                        passwords: 'admin/passwords'
                      }

  resource :corporate_connections

  get :spend_vs_budgets_data, to: 'pages#spend_vs_budgets_data'

  authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  authenticated :admin do
    root 'pages#dashboard', as: :admin_authenticated_root
  end

  devise_scope :user do
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
    namespace :users, as: :user do
      put "/confirm" => "confirmations#confirm", as: :confirm
      put '/switch_current_property', to: 'sessions#switch_current_property', as: :switch_current_property
      resource :registration, only: [:edit, :update]
    end
  end
  resources :property_settings, path: 'settings', only: [:index]
  resources :categories, :locations, :lists do
    get 'rearrange', on: :member
    get 'destroy', on: :collection, path: 'destroy', as: 'destroy'
  end  
  resources :items do
    collection do
      get 'start_order'
      get 'edit_multiple_tags'
      put 'update_multiple_tags'
      get :new_import
      post :import
      get 'destroy', path: 'destroy', as: 'destroy'
    end
  end
  resources :permissions, only: [:index] do
    collection do
      post 'update_all'
    end
  end
  resources :properties, only: [:show, :index, :update]
  resources :tags do
    get 'rearrange', on: :member
  end
  resources :purchase_orders, except: [:edit, :new, :create], path: 'orders' do
    member do
      post :send_fax, to: 'fax#create'
      get :fax_status, to: 'fax#show'
      post :update_fax, to: 'fax#update'
      post :send_email, to: 'email#create'
      post :send_vpt, to: 'vpt#create'
      get :print
    end
  end
  resources :purchase_receipts, only: [:new, :create], path: 'receipts'
  resources :purchase_requests, path: 'requests' do
    member do
      get :inventory_print
    end
  end
  resources :users do
    member do
      get :change_password
    end
  end
  resources :messages
  resources :budgets

  resources :reports do
    member do
      put :favorite
    end
    collection do
      get :favorites
      #get *Report.pluck(:permalink).map{|p| p + '_data'} if Report.any?
      get :trending_cloud
      scope :render do
        get :vendor_spend
        get :category_spend
        get :items_consumption
        get :item_orders_chart_data
        get :items_spend
        get :item_price_variance
        get :inventory_vs_ordering
        get :maintenance_work_orders
        get :pm_productivity_report
        get :maintenance_pm_productivity_data
        get :room_pm_progress_data
        get :work_order_productivity_data
        get :guest_room_pm_analysis
        get :public_area_pm_analysis
        get :equipment_pm_analysis
        get :work_order_trendings
      end
    end
  end


  resources :vendors
  resources :room_types
  resources :departments
  resources :notifications
  resources :activities, only: [:index]
  resources :join_invitations do
    get 'accept', on: :member
  end
  resources :guest_logs do
    get 'like', on: :member
    post 'set_alarm', on: :collection
    get 'check_alarm', on: :member
    delete 'remove_alarm', on: :member
  end

  post 'punchout/:property_id/:vendor_id/shopping_cart', to: "punchout#shopping_cart", as: 'punchout_shopping_cart'
  get 'punchout/:property_id/:vendor_id', to: "punchout#create", as: 'start_punchout'

  get 'analytics', to: "analytics#index"
  get 'forecasts/(week/:year/:month/:day)', to: "forecasts#index", as: "forecasts"
  put 'forecast', to: "forecasts#update", as: "update_forecast"

  get '/fax', to: 'fax#show'
  post '/fax', to: 'fax#create'
  post '/phaxio', to: 'fax#update'
  get 'dashboard', to: 'pages#dashboard', :as => :dashboard
  get 'pages/home'
  # authenticated :user do
  #   root to: 'pages#dashboard'
  # end

  #root to: 'users/sessions#new'  
  if Rails.env.development? or Rails.env.qa?
    mount MailerPreview => 'mailer_view'
    mount Sidekiq::Web, at: '/sidekiq'
  end

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :report_favoritings
  has_many :favoriting_users, through: :report_favoritings, source: :user
  has_many :report_runs

  scope :for_maintenance, -> { where('groups ILIKE ?', 'maintenance') }

  ALL_KINDS = [
    {permalink: 'vendor_spend', name: 'Vendor Spend', description: "Provides analysis of the total spending on your Vendors.  Useful to understand who are your top Vendors to negotiate contracts with.", groups: 'spending' },
    {permalink: 'category_spend', name: 'Category Spend', description: "Understand your Hotel's spending by Category. Analyze which categories comprise most of your hotel's spending", groups: 'spending' },
    {permalink: 'items_spend', name: 'Items Spend', description: "Analyze which items comprise 80% of your spending. Optimize the procurement and inventory to reduce costs.", groups: 'spending' }, {permalink: 'purchase_history_report', name: 'Purchase History Report', description: "Understand your Hotel's spending by Category. Analyze which categories comprise most of your hotel's spending", groups: 'purchases' },
    # {permalink: 'budget_vs_spend', name: 'Budget vs Spend', description: "Description goes here", groups: 'budget' },
    # {permalink: 'cpor_analysis', name: 'CPOR Analysis', description: "Description goes here", groups: 'budget' },
    # {permalink: 'vendor_list', name: 'Vendor List', description: "Description goes here", groups: 'misc' },
    # {permalink: 'list_item_coverage', name: 'List Item Coverage', description: "Description goes here", groups: 'misc' },
    {permalink: 'items_consumption', name: 'Items Consumption', description: "Consumption Report allows you to analyze the frequency, size and value of your Ordering for individual items to understand and compare your consumption between periods.", groups: 'purchases,misc' },
    {permalink: 'item_price_variance', name: 'Item Price Variance', description: "Provides data from Item's Received Orders to analyze the variation in the PO price and the Actual price an item is received at.", groups: 'spending,misc' },
    # {permalink: 'inventory_vs_ordering', name: 'Inventory vs Ordering', description: "...", groups: 'purchases, misc' },
    {permalink: 'maintenance_work_orders', name: 'Work Order Listing', description: "View all work orders for the hotel.", groups: 'maintenance' },
    {permalink: 'pm_productivity_report', name: 'PM Productivity Report', description: "Analyze the productivity of the Maintenance department", groups: 'maintenance' },
    {permalink: 'guest_room_pm_analysis', name: 'Guest Room PM Analysis', description: "Understand the Guest Room PM status for the current Quarter, and analyze the history of PM completions.", groups: 'maintenance' },
    {permalink: 'public_area_pm_analysis', name: 'Public Area PM Analysis', description: "Understand the Public Area PM status for the current Quarter, and analyze the history of PM completions.", groups: 'maintenance' },
    {permalink: 'equipment_pm_analysis', name: 'Equipment PM Analysis', description: "Understand the Equipment PM status for the current Quarter, and analyze the history of PM completions.", groups: 'maintenance' },
    {permalink: 'work_order_trendings', name: 'Hotel Trending Issue', description: "The trending issues report will allow managers to understand the frequently seen issues during PMs and Work Orders in a given period of time", groups: 'maintenance' }
  ]

  def groups_as_array
    self.groups.split(',').map(&:strip)
  end

  def toggle_favorited_by!(user)
    if favorited_by?(user)
      favoriting_users.delete(user)
    else
      favoriting_users << user
    end
  end

  def favorited_by?(user)
    favoriting_users.include?(user)
  end

  def record_run_by!(user)
    report_runs.create(user: user)
  end

  def last_run
    @last_run ||= report_runs.order(:created_at).last
  end

  def last_run_by_name
    last_run.user.name
  end

 def last_run_at
   last_run.created_at
 end
end

app/controllers/corporate/reports_controller.rb
class Corporate::ReportsController < Corporate::BaseController
  def index
    
  end
end

app/helpers/report_helper.rb
module ReportHelper
  def room_status(record)
    return if record.nil?
    status = ''
    detail = ''
    if record[:status] == :completed
      status = "<i class='fa fa-info-circle text-primary'></i>"
    end

    if record[:status] == :_remaining
      status += "<i class='fa fa-times-circle text-danger'></i>"
    else
      status += "<i class='fa fa-check text-success'></i>"
      status += " (#{record[:count_of_pm]} <b class='text-default'>PMs</b>)" if record[:count_of_pm] > 1
    end

    if (record[:fixed] && record[:fixed] > 0)
      detail += "<br>#{record[:fixed]} <b class='text-default'>fixes</b>"
    end
    if (record[:issues] && record[:issues] > 0)
      detail += "<br>#{record[:issues]} <b class='text-default'>WOs</b>"
    end
    "#{status}#{detail}".html_safe
  end

  def area_status(record)
    return if record.nil?
    status = ''
    detail = ''
    if record[:status] == :completed
      status = "<i class='fa fa-info-circle text-primary'></i>"
    end

    if record[:status] == :_remaining
      status += "<i class='fa fa-times-circle text-danger'></i>"
    else
      status += "<i class='fa fa-check text-success'></i>"
      status += " (#{record[:count_of_pm]} <b class='text-default'>PMs</b>)" if record[:count_of_pm] > 1
    end

    if (record[:fixed].count > 0)
      detail += "<br>#{record[:fixed].count} <b class='text-default'>fixes</b>"
    end
    if (record[:issues].count > 0)
      detail += "<br>#{record[:issues].count} <b class='text-default'>WOs</b>"
    end
    "#{status}#{detail}".html_safe
  end

  def pdf_image_tag(image, options = {})
    options[:src] = 'file:///' + File.expand_path(Rails.root) + '/vendor' + image
    options[:src]
  end

  # Convert cycle to quarter
  def c2q(cycle, cycle_type=:room)
    current_cycle(cycle_type).frequency_months == 3 ? "Q#{cycle}" : "C#{cycle}"
  end
end

app/views/reports/_report.html.slim
.col-xs-12.col-sm-6.col-md-4.shuffle data-groups=report.groups_as_array
  .widget.panel class=('favorite' if report.favorited_by?(current_user))
    =link_to '#', data: { tooltip_active: t('.report_fav'), tooltip_inactive: t('.report_nonfav'), href: favorite_report_path(report), toggle: "tooltip", placement:'left'},
      class: "favorite panel-ribbon pull-right" do
        i.ico-heart3
        i.ico-heart4
    .panel-body
      ul.list-unstyled
        li.text-center
          h4.semibold.mb0.report-name.search-target= link_to report.name, report_path(report.permalink)
          br
          p.nm.text-muted= report.description
      hr/
      .mt10.text-muted.text-center
        -if report.report_runs.present?
          ' Last run on:
          strong<>= l(report.last_run_at, format: :short) 
          ' By:
          strong<>= report.last_run_by_name
        - else
          ' Last run: Never

app/views/reports/category_spend.html.slim
.page-header.page-header-block
  .page-header-section
    h4.title.semibold
      | Category Spend
      .pull-right#table-actions
.row
  .report-sidebar.col-md-4
    .panel.panel-default
      .panel-body
        .row.mb10
          .col-md-12
            span.radio.custom-radio.custom-radio-primary  
              input#filter-option-1 name="sort_type" value="0" type="radio"
              label for="filter-option-1" &nbsp; Top 5 categories
        .row.mb10
          .col-md-12
            span.radio.custom-radio.custom-radio-primary  
              input#filter-option-2 name="sort_type" value="1" type="radio"
              label for="filter-option-2"  &nbsp; Top 10 categories
        .row.mb10
          .col-md-12
            span.radio.custom-radio.custom-radio-primary  
              input#filter-option-3 name="sort_type" value="2" type="radio"
              label for="filter-option-3"  &nbsp; Select categories
        .row
          .col-md-12
            select#categories-filter.form-control multiple="multiple" placeholder=("Select category...") 
              option value=""  Select a category...
              = options_from_collection_for_select Category.all, :id, :name
        .form-group
  
  .report-body.col-md-8
    .panel.panel-inverse
      .panel-heading
        .fc.fc-ltr.fc-unthemed#calendar-control
          .fc-toolbar
            .fc-left
              .fc-button-group
                a.fc-button.fc-state-default.fc-corner-left#offset-minus <
                a.fc-button.fc-state-default.fc-corner-right#offset-plus >
            .fc-right
              .fc-button-group.date-range-type
                a.fc-button.fc-state-default.fc-corner-left data-value="today" Today
                a.fc-button.fc-state-default data-value="month" Month
                a.fc-button.fc-state-default data-value="week" Week
                a.fc-button.fc-state-default.fc-corner-right data-value="day" Day
            .fc-center
              h2.text-center#date-range-indicator ...

      .panel-collapse.pull.out

        table.searchable-table.table.no-bottom-border.table-hover#report-data
          thead
            tr
              th.text-center Category Name
              th.text-center width="150px" Received Orders
              th.text-center width="150px" Amount Spent
              th.text-center width="150px" % of Total Spending

        #loading.indicator
          span.spinner

javascript:
  export_filename = "Category Spend Report - " + moment().format("YYYY.MM.DD") + " - #{current_user.name}"
coffee:
  $(document).ready ->
    dateRange          = new DateRange('month')
    dateRangeIndicator = $('#date-range-indicator')
    loading            = $('#loading')
    $categoriesFilter     = undefined
    categoriesFilter      = undefined

    # DataTables initialization:
    table = $('table#report-data').DataTable(
      dom: 'Trt'
      "aoColumnDefs": [
        { 'bSortable': false, 'aTargets': [ 'nosort' ] }
      ]
      "fnRowCallback": ( nRow, aData, iDisplayIndex, iDisplayIndexFull ) ->
        $('td:eq(2)', nRow).addClass( "success" )
      "order": [[ 3, "desc" ]]
      oTableTools:
        sSwfPath: "/assets/adminre_theme_v120/plugins/datatables/tabletools/swf/copy_csv_xls_pdf.swf"
        aButtons: [
            "sExtends": "print",
          ,
            "sExtends": "pdf",
            "sFileName": export_filename + ".pdf"
          ,
            "sExtends": "csv",
            "sFileName": export_filename + ".csv"
        ]
    )

    $('.DTTT').appendTo('#table-actions')


    loadData = ->
      # disabling offset buttons if chosen "Today"
      $('#offset-minus, #offset-plus').toggle(dateRange.type isnt 'today')

      dateRangeIndicator.text(dateRange)
      loading.show()

      $.debounce(1000, ->
        $.ajax({
          dataType: 'json'
          type: "GET"
          url: Routes.report_path("render/category_spend")
          data: { from: dateRange.from4rails(), to: dateRange.to4rails() }
          success: (data)->
            table.clear().draw()
            $(data).each (i, el)->

              table.row.add( [
                el.category_name
                "<div class='text-center'>#{el.num_orders}</div>"
                "<div class='text-center'><span class='text-muted bold'>$#{ formatPrice(el.spend) }</span></div>"
                "<div class='text-center'>#{ Math.round(el.percentage_of_spend) }%</div>"
              ] ).draw()
            sortAndOrder()
          complete: -> loading.hide()
        })
      )()


    # loading dara after page render complete:
    loadData()

    selectedCategoriesFilter = {}

    sortAndOrder = ->
      filter = $('input:radio[name="sort_type"]:checked').val()
      table.columns(0).search("").page.len(-1) # resetting previous filters
      categoriesFilter.disable()

      if filter is "0"      # top 5 categories
        categoriesFilter.clear()
        table.order( [ 3, 'desc' ] ).page.len(5).draw()
      else if filter is "1" # top 10 categories
        categoriesFilter.clear()
        table.order( [ 3, 'desc' ] ).page.len(10).draw()
      else if filter is "2"
        categoriesFilter.enable()
        filterByCategory()
      else
        table.order( [3, 'desc'] ).page.len(-1).draw()

    filterByCategory = ->
      filterTermsArray = (val for key, val of selectedCategoriesFilter)
      # escaping search string for using in the regexp:
      filterTermsArray = $.map(filterTermsArray, (term)-> term.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&") )
      table.columns(0).search( filterTermsArray.join("|"), true, false).draw()

    $categoriesFilter = $('#categories-filter').selectize(
      onItemAdd: (value, data)->
        selectedCategoriesFilter[value] = $(data).text()
        filterByCategory()
      onItemRemove: (value)->
        delete selectedCategoriesFilter[value]
        filterByCategory()
    )

    categoriesFilter = $categoriesFilter[0].selectize

    $('input:radio[name="sort_type"]').on 'change', sortAndOrder

    # events handlers:
    $('.date-range-type > a').on('click', ->
      $(this).parent().find('a').removeClass('fc-state-active')
      $(this).addClass 'fc-state-active'
      if dateRange.type isnt $(this).data('value') # reset all offsets if changed $range type
        dateRange.setType($(this).data('value'))
        loadData()
    )

    $(".date-range-type > a[data-value='#{ dateRange.type }']").trigger('click')

    $('#offset-minus').on 'click', -> dateRange.backward(); loadData()
    $('#offset-plus').on 'click', -> dateRange.forward(); loadData()

app/views/reports/index.html.slim
.page-header.page-header-block
  .page-header-section
    h4.title.semibold=  @title 
  .page-header-section
    .toolbar.clearfix
      .col-md-8
        #filter-options.btn-group
          button.btn.btn-default data-group="spending"  Spending
          button.btn.btn-default data-group="purchases"  Purchases
          button.btn.btn-default data-group="budget"  Budget
          button.btn.btn-default data-group="misc"  Misc
          button.btn.btn-default data-group="maintenance"  Maintenance

      .col-md-3.pull-right
        .has-icon
          input#shuffle-filter.form-control name="shuffle-filter" placeholder=("Search reports") type="search" /
          i.ico-search.form-control-icon

#shuffle-grid.report-listing.row
  = render @reports

a.totop.animation data-hideanim="bounceOut" data-offset="50%" data-showanim="bounceIn" data-toggle=("waypoints totop") href="#" 
  i.ico-angle-up

app/views/reports/items_spend.html.slim
.page-header.page-header-block
  .page-header-section
    h4.title.semibold
      | Item Spend
      .pull-right#table-actions
.row
  .report-sidebar.col-md-4
    .panel.panel-default
      .panel-body
        .row.mb10
          .col-md-12
            span.radio.custom-radio.custom-radio-primary  
              input#filter-option-1 name="sort_type" value="0" type="radio"
              label for="filter-option-1" &nbsp; Top 5 items
        .row.mb10
          .col-md-12
            span.radio.custom-radio.custom-radio-primary  
              input#filter-option-2 name="sort_type" value="1" type="radio"
              label for="filter-option-2"  &nbsp; Top 10 items
        .row.mb10
          .col-md-12
            span.radio.custom-radio.custom-radio-primary  
              input#filter-option-3 name="sort_type" value="2" type="radio"
              label for="filter-option-3"  &nbsp; Select items
        .row
          .col-md-12
            select#items-filter.form-control multiple="multiple" placeholder=("Select item...") 
              option value=""  Select a item...
              = options_from_collection_for_select Item.all, :id, :name
        .form-group
  
  .report-body.col-md-8
    .panel.panel-inverse
      .panel-heading
        .fc.fc-ltr.fc-unthemed#calendar-control
          .fc-toolbar
            .fc-left
              .fc-button-group
                a.fc-button.fc-state-default.fc-corner-left#offset-minus <
                a.fc-button.fc-state-default.fc-corner-right#offset-plus >
            .fc-right
              .fc-button-group.date-range-type
                a.fc-button.fc-state-default.fc-corner-left data-value="today" today
                a.fc-button.fc-state-default data-value="month" month
                a.fc-button.fc-state-default data-value="week" week
                a.fc-button.fc-state-default.fc-corner-right data-value="day" day

            .fc-center
              h2.text-center#date-range-indicator ...

      .panel-collapse.pull.out

        table.searchable-table.table.no-bottom-border.table-hover#report-data
          thead
            tr
              th.text-center Item Name
              th.text-center width="150px" Received Orders
              th.text-center width="150px" Amount Spent
              th.text-center width="150px" % of Total Spending

        #loading.indicator
          span.spinner

  javascript:
    export_filename = "Items Spend Report - " + moment().format("YYYY.MM.DD") + " - #{current_user.name}"
  coffee:
    $(document).ready ->
      dateRangeIndicator = $('#date-range-indicator')
      loading            = $('#loading')
      dateRange          = new DateRange('month')
      $itemsFilter     = undefined
      itemsFilter      = undefined

      # DataTables initialization:
      table = $('table#report-data').DataTable
        dom: 'Trt'
        aoColumnDefs: [
          { 'bSortable': false, 'aTargets': [ 'nosort' ] }
        ],
        fnRowCallback: ( nRow, aData, iDisplayIndex, iDisplayIndexFull ) ->
          $('td:eq(2)', nRow).addClass( "success" )
        fnSort: [[ 3, "desc" ]]
        oTableTools:
          sSwfPath: "/assets/adminre_theme_v120/plugins/datatables/tabletools/swf/copy_csv_xls_pdf.swf"
          aButtons: [
              "sExtends": "print",
            ,
              "sExtends": "pdf",
              "sFileName": export_filename + ".pdf"
            ,
              "sExtends": "csv",
              "sFileName": export_filename + ".csv"
          ]

      $('.DTTT').appendTo('#table-actions')

      loadData = ->
        # disabling offset buttons if chosen "Today"
        $('#offset-minus, #offset-plus').toggle(dateRange.type isnt 'today')
        dateRangeIndicator.text(dateRange)
        
        loading.show()

        $.debounce(1000, ->
          $.ajax({
            dataType: 'json'
            type: "GET"
            url: Routes.report_path("render/items_spend")
            data: { from: dateRange.from4rails(), to: dateRange.to4rails() }
            success: (data)->
              table.clear().draw()
              $(data).each (i, el)->

                table.row.add( [
                  el.name
                  "<div class='text-center'>#{el.num_orders}</div>"
                  "<div class='text-center'><span class='text-muted bold'>$#{ formatPrice(el.spend) }</span></div>"
                  "<div class='text-center'>#{ Math.round(el.percentage_of_spend) }%</div>"
                ] ).draw()
              sortAndOrder()
              filterByItem()
            complete: -> loading.hide()
          })
        )()


      # loading dara after page render complete:
      loadData()

      selectedCategoriesFilter = {}

      sortAndOrder = ->
        filter = $('input:radio[name="sort_type"]:checked').val()
        table.columns(0).search("").page.len(-1) # resetting previous filters
        itemsFilter.disable()

        if filter is "0"      # top 5 items
          itemsFilter.clear()
          table.order( [ 3, 'desc' ] ).page.len(5).draw()
        else if filter is "1" # top 10 items
          itemsFilter.clear()
          table.order( [ 3, 'desc' ] ).page.len(10).draw()
        else if filter is "2"
          itemsFilter.enable()
        else
          table.order( [3, 'desc'] ).page.len(-1).draw()
          
      filterByItem = ->
        filterTermsArray = (val for key, val of selectedCategoriesFilter)
        # escaping search string for using in the regexp:
        filterTermsArray = $.map(filterTermsArray, (term)-> term.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&") )
        table.columns(0).search( filterTermsArray.join("|"), true, false).draw()

      $itemsFilter = $('#items-filter').selectize(
        onItemAdd: (value, data)->
          selectedCategoriesFilter[value] = $(data).text()
          filterByItem()
        onItemRemove: (value)->
          delete selectedCategoriesFilter[value]
          filterByItem()
      )

      itemsFilter = $itemsFilter[0].selectize

      $('input:radio[name="sort_type"]').on 'change', sortAndOrder

      # events handlers:
      $('.date-range-type > a').on('click', ->
        $(this).parent().find('a').removeClass('fc-state-active')
        $(this).addClass 'fc-state-active'
        if dateRange.type isnt $(this).data('value') # reset all offsets if changed $range type
          dateRange.setType($(this).data('value'))
          loadData()
      )

      $(".date-range-type > a[data-value='#{ dateRange.type }']").trigger('click')

      $('#offset-minus').on 'click', -> dateRange.backward(); loadData()
      $('#offset-plus').on 'click', -> dateRange.forward(); loadData()

app/views/reports/show.html.slim
#report-content

- content_for :js do
  javascript:
    $('#report-content').load(Routes.report_path("render/#{params[:id]}", #{raw params.to_json}))